# Generated by Django 5.2.6 on 2025-09-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
